src/main/java/kp/company/domain/Employee.java
package kp.company.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Simple JavaBean domain object representing an employee. The 'equals()' and
 * 'hashCode()' methods are overridden because instances of subclasses are in
 * Sets.
 */
@Entity
@Table(name = "EMPLOYEES")
public class Employee {

	@Id
	@GeneratedValue
	@Column(name = "id")
	private Long id;

	@Column(name = "first_name")
	private String firstName;

	@Column(name = "last_name")
	private String lastName;

	@ManyToOne
	@JoinColumn(name = "department_id")
	private Department department;

	@ManyToOne
	@JoinColumn(name = "title_id")
	private Title title;

	/**
	 * Constructor.
	 */
	public Employee() {
	}

	/**
	 * Sets id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {

		this.id = id;
	}

	/**
	 * Gets id.
	 * 
	 * @return id
	 */
	public Long getId() {

		return id;
	}

	/**
	 * Sets first name.
	 * 
	 * @param firstName
	 *            first name
	 */
	public void setFirstName(String firstName) {

		this.firstName = firstName;
	}

	/**
	 * Gets first name.
	 * 
	 * @return first name
	 */
	public String getFirstName() {

		return this.firstName;
	}

	/**
	 * Sets last name.
	 * 
	 * @param lastName
	 *            last name
	 */
	public void setLastName(String lastName) {

		this.lastName = lastName;
	}

	/**
	 * Gets last name.
	 * 
	 * @return last name
	 */
	public String getLastName() {

		return this.lastName;
	}

	/**
	 * Sets department.
	 * 
	 * @param department
	 *            department
	 */
	public void setDepartment(Department department) {

		this.department = department;
	}

	/**
	 * Gets department.
	 * 
	 * @return department
	 */
	public Department getDepartment() {

		return this.department;
	}

	/**
	 * Sets title.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(Title title) {

		this.title = title;
	}

	/**
	 * Gets title.
	 * 
	 * @return title title
	 */
	public Title getTitle() {

		return this.title;
	}

	/**
	 * Indicates whether some other object is "equal to" this one.
	 * 
	 * @param other
	 *            other object
	 * @return result the result
	 */
	public boolean equals(Object other) {

		if (this == other) {
			return true;
		}
		if (!(other instanceof Employee)) {
			return false;
		}
		final Employee employee = (Employee) other;
		if (employee.getId() == null || !employee.getId().equals(this.getId())) {
			return false;
		}
		return true;
	}

	/**
	 * Returns a hash code value for the object.
	 * 
	 * @return hashCode
	 */
	public int hashCode() {

		int result = 0;
		if (this.getId() != null) {
			result = 29 * this.getId().intValue();
		}
		return result;
	}

}

src/main/java/kp/company/web/CompanyBackingBean.java
package kp.company.web;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;

import kp.company.BusinessLogic;
import kp.company.domain.Department;
import kp.company.domain.Employee;
import kp.company.domain.Title;
import kp.company.exc.KpException;
import kp.company.util.LoggingConfiguration;

/**
 * Company backing bean, that is backed to xhtml pages.
 * 
 */
@ManagedBean
@SessionScoped
public class CompanyBackingBean implements Serializable {
	private static final Logger logger = Logger.getLogger(CompanyBackingBean.class.getName());

	private static final long serialVersionUID = 1L;

	private BusinessLogic businessLogic = null;
	private Department department = null;
	private Employee employee = null;
	private Long selectedTitleId = null;

	/**
	 * Default empty constructor.
	 */
	public CompanyBackingBean() {

		LoggingConfiguration.setLogging();	
		businessLogic = new BusinessLogic();
		if (logger.isLoggable(Level.INFO)) {
			logger.info("CompanyBackingBean():");
		}
	}

	/**
	 * Sets department.
	 * 
	 * @param department
	 *            the department to set
	 */
	public void setDepartment(Department department) {

		this.department = department;
	}

	/**
	 * Gets department.
	 * 
	 * @return the department
	 */
	public Department getDepartment() {

		return department;
	}

	/**
	 * Sets employee.
	 * 
	 * @param employee
	 *            the employee to set
	 */
	public void setEmployee(Employee employee) {

		this.employee = employee;
	}

	/**
	 * Gets employee.
	 * 
	 * @return the employee
	 */
	public Employee getEmployee() {

		return employee;
	}

	/**
	 * Sets selected title id.
	 * 
	 * @param selectedTitleId
	 *            the selected title id to set
	 */
	public void setSelectedTitleId(Long selectedTitleId) {

		this.selectedTitleId = selectedTitleId;
	}

	/**
	 * Gets selected title id.
	 * 
	 * @return the titleSelectItem
	 */
	public Long getSelectedTitleId() {

		return selectedTitleId;
	}

	/**
	 * Gets departments.
	 * 
	 * @return list of departments
	 * @throws KpException
	 *             the exception
	 */
	public List<Department> getDepartments() throws KpException {

		List<Department> departments = businessLogic.loadDepartments();
		if (logger.isLoggable(Level.INFO)) {
			logger.info("getDepartments():");
		}
		return departments;
	}

	/**
	 * Gets employees.
	 * 
	 * @return list of departments
	 * @throws KpException
	 *             the exception
	 */
	public List<Employee> getEmployees() throws KpException {

		if (department == null) {
			logger.severe("getEmployees(): department == null");
			return null;
		}
		List<Employee> employees = businessLogic.loadEmployees(department.getId());
		if (logger.isLoggable(Level.INFO)) {
			logger.info("getEmployees():");
		}
		return employees;
	}

	/**
	 * Gets title select items.
	 * 
	 * @return list of title select items
	 * @throws KpException
	 *             the exception
	 */
	public List<SelectItem> getTitleSelectItems() throws KpException {

		List<Title> titles = businessLogic.loadTitles();
		List<SelectItem> titleSelectItem = new ArrayList<SelectItem>();
		for (Title t : titles) {
			SelectItem selectItem = new SelectItem(t.getId(), t.getName());
			titleSelectItem.add(selectItem);
		}
		if (employee != null && employee.getTitle() != null) {
			selectedTitleId = employee.getTitle().getId();
		} else {
			selectedTitleId = 0L;
		}
		if (logger.isLoggable(Level.CONFIG)) {
			logger.config("getTitleSelectItems():");
		}
		return titleSelectItem;
	}

	/**
	 * List departments. Wrapper for "kp:columnCommand" tag.
	 * 
	 * @return outcome the outcome
	 */
	public String listDepartments() {

		return "listDepartments";
	}

	/**
	 * Lists employees. Wrapper for "kp:columnCommand" tag.
	 * 
	 * @return outcome the outcome
	 */
	public String listEmployees() {

		return "listEmployees";
	}

	/**
	 * Edits department. Wrapper for "kp:columnCommand" tag.
	 * 
	 * @return outcome the outcome
	 */
	public String editDepartment() {

		return "editDepartment";
	}

	/**
	 * Confirms deleting department. Wrapper for "kp:columnCommand" tag.
	 * 
	 * @return outcome the outcome
	 */
	public String confirmDeleteDepartment() {

		return "confirmDeleteDepartment";
	}

	/**
	 * Edits employee. Wrapper for "kp:columnCommand" tag.
	 * 
	 * @return outcome the outcome
	 */
	public String editEmployee() {

		return "editEmployee";
	}

	/**
	 * Confirms deleting department. Wrapper for "kp:columnCommand" tag.
	 * 
	 * @return outcome the outcome
	 */
	public String confirmDeleteEmployee() {

		return "confirmDeleteEmployee";
	}

	/**
	 * Prepares adding new department.
	 * 
	 * @return outcome the outcome
	 */
	public String prepareAddDepartment() {

		department = new Department();
		String outcome = "editDepartment";
		if (logger.isLoggable(Level.INFO)) {
			logger.info("prepareAddDepartment(): outcome[" + outcome + "]");
		}
		return outcome;
	}

	/**
	 * Updates department.
	 * 
	 * @return outcome the outcome
	 * @throws KpException
	 *             the exception
	 */
	public String updateDepartment() throws KpException {

		businessLogic.storeDepartment(department);
		String outcome = "listDepartments";
		if (logger.isLoggable(Level.INFO)) {
			logger.info("updateDepartment(): outcome[" + outcome + "]");
		}
		return outcome;
	}

	/**
	 * Deletes department.
	 * 
	 * @return outcome the outcome
	 * @throws KpException
	 *             the exception
	 */
	public String deleteDepartment() throws KpException {

		businessLogic.deleteDepartment(department.getId());
		String outcome = "listDepartments";
		if (logger.isLoggable(Level.INFO)) {
			logger.info("deleteDepartment(): outcome[" + outcome + "]");
		}
		return outcome;
	}

	/**
	 * Prepares adding new employee.
	 * 
	 * @return the employee
	 */
	public String prepareAddEmployee() {

		employee = new Employee();
		if (department != null) {
			employee.setDepartment(department);
		}
		String outcome = "editEmployee";
		if (logger.isLoggable(Level.INFO)) {
			logger.info("prepareAddDepartment(): outcome[" + outcome + "]");
		}
		return outcome;
	}

	/**
	 * Updates employee.
	 * 
	 * @return outcome the outcome
	 * @throws KpException
	 *             the exception
	 */
	public String updateEmployee() throws KpException {

		List<Title> titles = businessLogic.loadTitles();
		for (Title title : titles) {
			if (selectedTitleId.equals(title.getId())) {
				employee.setTitle(title);
			}
		}
		businessLogic.storeEmployee(employee);
		String outcome = "listEmployees";
		if (logger.isLoggable(Level.INFO)) {
			logger.info("updateEmployee(): outcome[" + outcome + "]");
		}
		return outcome;
	}

	/**
	 * Deletes employee.
	 * 
	 * @return outcome the outcome
	 * @throws KpException
	 *             the exception
	 */
	public String deleteEmployee() throws KpException {

		businessLogic.deleteEmployee(employee.getId());
		String outcome = "listEmployees";
		if (logger.isLoggable(Level.INFO)) {
			logger.info("deleteEmployee(): outcome[" + outcome + "]");
		}
		return outcome;
	}

}

src/main/webapp/pages/employees/confirmDelete.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:kp="http://www.example.org/jsf"
                template="/WEB-INF/templates/template.xhtml">

  <ui:define name="menu">
    <ui:include src="/pages/siteNavigation.xhtml">
      <ui:param name="page" value="7"/>
    </ui:include>
  </ui:define>
  
  <ui:define name="content">
    <div class="form">
      Delete employee&#160;
      <h:outputText class="form-field-read-only"
        value="#{companyBackingBean.employee.firstName} #{companyBackingBean.employee.lastName}" />
      ?
    </div>
      
    <kp:buttonsOkCancel actionOk="deleteEmployee" actionCancel="listEmployees"
                        backingBean="#{companyBackingBean}"/>
  </ui:define>
</ui:composition>

src/main/webapp/pages/employees/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:kp="http://www.example.org/jsf"
                template="/WEB-INF/templates/template.xhtml">


  <ui:define name="menu">
    <ui:include src="/pages/siteNavigation.xhtml">
      <ui:param name="page" value="6"/>
    </ui:include>
  </ui:define>

  <ui:define name="content">
    <div class="form" >
      <h:panelGrid columns="2"
                   columnClasses="form-prompt,form-field"
                   rules="rows">

        <kp:fieldReadOnly label="Department" fieldName="name"
                          entity="#{companyBackingBean.department}"/>

        <kp:field label="First Name" fieldName="firstName"
                  entity="#{companyBackingBean.employee}"/>
                  
        <kp:field label="Last Name" fieldName="lastName"
                  entity="#{companyBackingBean.employee}"/>
                     
        <h:outputText value="Title"/>
        <h:selectOneMenu value="#{companyBackingBean.selectedTitleId}">
          <f:selectItems value="#{companyBackingBean.titleSelectItems}"/>
        </h:selectOneMenu>
      </h:panelGrid>
    </div>
    <div style="clear:both;" ></div>
      
    <h:messages styleClass="errors"/>
      
    <kp:buttonsOkCancel actionOk="updateEmployee" actionCancel="listEmployees"
                        backingBean="#{companyBackingBean}"/>
  </ui:define>
</ui:composition>

src/main/webapp/pages/employees/list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:kp="http://www.example.org/jsf"
                template="/WEB-INF/templates/template.xhtml">

  <ui:define name="menu">
    <ui:include src="/pages/siteNavigation.xhtml">
      <ui:param name="page" value="5"/>
    </ui:include>
  </ui:define>

  <ui:define name="content">
    <div class="form" >
      <h:panelGrid columns="2"
                   columnClasses="form-prompt,form-field"
                   rules="rows">

        <kp:fieldReadOnly label="Department" fieldName="name"
                          entity="#{companyBackingBean.department}"/>
      </h:panelGrid>
    </div>
      
    <h:dataTable border="1"
                 cellpadding="5px"
                 columnClasses="list-col,list-col,list-col,list-link-2,list-link-3"
                 frame="box"
                 headerClass="list-header"
                 rowClasses="list-row"
                 rules="all"
                 styleClass="list-all"
                 summary="departments"
                 value="#{companyBackingBean.employees}"
                 var="employee">

      <kp:column label="First Name" fieldName="firstName" entity="#{employee}"/>

      <kp:column label="Last Name" fieldName="lastName" entity="#{employee}"/>

      <kp:column label="Title" fieldName="name" entity="#{employee.title}"/>
                   
      <kp:columnCommand label="Edit" action="editEmployee"
                        target="employee" source="#{employee}"
                        backingBean="#{companyBackingBean}"/>
                       
      <kp:columnCommand label="Delete" action="confirmDeleteEmployee"
                        target="employee" source="#{employee}"
                        backingBean="#{companyBackingBean}"/>
    </h:dataTable>

    <div class="links" ></div>
      
    <div class="links" >
      <p><h:commandLink action="#{companyBackingBean.prepareAddEmployee}">
        <h:outputText value="Add Employee" />
      </h:commandLink></p>
    </div>
  </ui:define>
</ui:composition>